apiVersion: v1
data:
  keys.conf: ICAgIG1hcCAkaHR0cF9hcGlrZXkgJGFwaV9rZXlfbmFtZSB7CiAgICBkZWZhdWx0ICIiOwoKICAgICJubnk2TnFDbXZnVmRBWEtmRW0yWGhOaHFsZmhzVUpLVVR4d3N4bktSVGRBSW5YMFRMTk5LaHY4SE5mbjB3SnV2IiAia2V5X29uZSI7CiAgICAic0dlbW55UndUUGpQN3pNYXY3a0xqalVTVzRmZTZKeTI0TEdjZ1BUcnVlVzRNRTFMZzhzYUlWQzA3cXpZNFNCUCIgImtleV90d28iOwogICAgIm9DY3VTSVJ6d1FMVzdiQWtkNzRhRDFPSGlVd2lvcGVhaGh6QjZ5cVB4aHB4RTlEV1F4WWdQem5IVHdBZFVRR3ciICJrZXlfdGhyZWUiOwogICAgIkExQ2dyQlFqVG00djVMSjR1aUZNNUdiekEzdGxxOFc3bnBueEZuWkZmZExJWng5ajZkN3Y0eWJBMlZWY2s1RkEiICJrZXlfZm91ciI7CiAgICAiYjBoUVpjRkl4ZG16dlMwcmZZVlVLcWE1a3Fzc0RaeVdHRlZKaWhMellkTFl6aWRVU09mVWtodDNna0F6alExNiIgImtleV9maXZlIjsKICAgIH0=
  keys2.conf: ICAgICAgICAgICAgICAgIG1hcCAkaHR0cF9hcGlrZXkgJGFwaV9rZXk2IHsKICAgICAgICAgICAgICAgICAgICBkZWZhdWx0ICIiOwogICAgICAgICAgICAgICAgICAgICJiYmJiYmIiICJkdmlyIjsKICAgICAgICAgICAgICAgIH0=
kind: Secret
metadata:
  name: nginx-keys-secret
  namespace: nginx-ingress
type: Opaque
