apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      custom.nginx.org/auth-api-key-pool: /coffee:1,/teaaa:2
      custom.nginx.org/auth-api-key-pool-store1: 1,22,333,4444,55555,666666,7777777
      custom.nginx.org/auth-api-key-pool-store2: A,BB,CCC,DDDD
  name: cafe-ingress
  namespace: cafe
spec:
  ingressClassName: nginx
  rules:
  - host: cafe.example.com
    http:
      paths:
      - backend:
          service:
            name: cafe-svc
            port:
              number: 80
        path: /teaaa
        pathType: Prefix
      - backend:
          service:
            name: cafe-svc
            port:
              number: 80
        path: /coffee
        pathType: Prefix
status:
  loadBalancer: {}
